name: E2E Tests

on:
  push:
    branches:
      - '**'        # tous les push sur toutes les branches
  pull_request:
    branches:
      - main        # ou master selon ton projet

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22
          cache: 'npm'

      - name: Installation des dépendances
        working-directory: ./frontend
        run: npm ci

      - name: Installation des navigateurs Playwright
        run: npx playwright install --with-deps chromium
        working-directory: ./frontend

      - name: Build de l'application
        working-directory: ./frontend
        run: npm run build

      - name: Démarrage de l'application en arrière-plan
        working-directory: ./frontend
        run: npm run dev &

      - name: Attendre que le serveur soit prêt
        working-directory: ./frontend
        run: npx wait-on http://localhost:5173 --timeout 30000

      - name: Lancement des tests Playwright
        working-directory: ./frontend
        run: npx playwright test

      - name: Upload du rapport en cas d'échec
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          working-directory: ./frontend
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 7
